//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
<<<<<<< HEAD
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
=======
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
>>>>>>> parent of 71d7b68... Như push QLTV
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SCORPION;Initial Catalog=QuanlyThuvien;Integrated Security=True")]
        public string QuanlyThuvienConnectionString {
            get {
                return ((string)(this["QuanlyThuvienConnectionString"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-FV6UJS5\\SQLEXPRESS;Initial Catalog=qltv;Integrated Security=T" +
            "rue")]
        public string qltvConnectionString {
            get {
                return ((string)(this["qltvConnectionString"]));
>>>>>>> parent of 71d7b68... Như push QLTV
            }
        }
    }
}
